# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: terraless
#env:
#  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - binary: terraless-provider-aws
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archive:
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

blobs:
  - provider: s3
    bucket: terraless-plugins
    folder: "terraless-provider-aws/{{ .Tag }}"
  - provider: s3
    bucket: terraless-plugins
    folder: "terraless-provider-aws/latest"
